### ISSUE TITLE
The function graph_split() seems to contradict the inductive scenarios.

### ISSUE THREAD

**Issue by Leon-0602** [snap-research/graphless-neural-networks#6]
I have a question about the function `graph_split` in the file _utils.py_. 

According to the code, the tensors **_idx_test_ind_** and **_obs_idx_train_** may overlap.

```py
def graph_split(idx_train, idx_val, idx_test, rate, seed):
    idx_test_ind, idx_test_tran = idx_split(idx_test, rate, seed)

    idx_obs = torch.cat([idx_train, idx_val, idx_test_tran])
    N1, N2 = idx_train.shape[0], idx_val.shape[0]
    obs_idx_all = torch.arange(idx_obs.shape[0])
    obs_idx_train = obs_idx_all[:N1]
    obs_idx_val = obs_idx_all[N1 : N1 + N2]
    obs_idx_test = obs_idx_all[N1 + N2 :]

    return obs_idx_train, obs_idx_val, obs_idx_test, idx_obs, idx_test_ind
```

For example, let _**V**_ = [0,1,2,3,4,5] be all nodes in the graph and _**idx_train**_ = [1,2], _**idx_val**_ = [3,4], _**idx_test**_ = [0, 5].

Suppose that _**idx_test_ind**_ = [0] and _**idx_test_tran**_ = [5] after the function _**idx_split()**_. Then we have _**idx_obs**_ = [1,2,3,4,5], N1=2, N2 = 2, and _**obs_idx_all**_ = [0,1,2,3,4]. Hence, the resulting observed sets are _**obs_idx_train**_ = [0,1], _**obs_idx_val**_ = [2,3], _**obs_idx_test**_ = [4].

This means that _**idx_test_ind**_ and _**obs_idx_train**_ both have the element 0, which contradicts the inductive scenario.

**Comment by ShichangZh** [comment]
Thank you for your question.

The reason why ***idx_test_ind*** and ***obs_idx_train*** can have the same element is because they correspond to two different indexing systems.

It is a bit complicated to create a proper inductive setting, though we try to make variable meanings clear in the function comments. 

```
Indices start with 'obs_' correspond to the node indices within the observed subgraph,
where as indices start directly with 'idx_' correspond to the node indices in the original graph
```

In other words, ***ind_*** covers [0, N], and ***obs_idx*** covers [0, N_{obs}], where the 0 in these two indexing systems corresponds to different nodes.

Let me explain it in more detail.

If you look at the following line in the ***run_inductive*** function, you will see that ***idx_obs*** is meant to index the original graph and construct the observed graph.

https://github.com/snap-research/graphless-neural-networks/blob/a24d570c82c906a8700ad33fc27209f6c1391343/train_and_eval.py#L324

This subgraph function will assign each node a new index. Later on, when creating a nodeloader in the following line, we pass ***obs_idx_train*** to the loader function to index the observed graph (subgraph). 

https://github.com/snap-research/graphless-neural-networks/blob/a24d570c82c906a8700ad33fc27209f6c1391343/train_and_eval.py#L336

In other words, ***obs_idx_train*** corresponds to the new indices created by the subgraph function.

I hope this helps. Please let me know if you have other questions.

**Comment by Leon-0602** [comment]
Thanks a lot for your clear explanations and patient help. I believe that GLNN and your future work will be very impactful. :)
